version: "3.1"
services:
  apigateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: backaged/carpediem-apigateway:v1
    command: serve-rest -c "/etc/config.yaml"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - auth
      - user
      - task
    volumes:
      - ./config.yaml:/etc/config.yaml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: backaged/carpediem-frontend:v1
    command: serve-rest -c "/etc/config.yaml"
    ports:
      - "3000:3000"
    volumes:
      - ./config.yaml:/etc/config.yaml
    
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: backaged/carpediem-auth:v1
    command: serve-rest -c "/etc/config.yaml"
    ports:
      - "3001:3001"
    volumes:
      - ./config.yaml:/etc/config.yaml

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: backaged/carpediem-user:v1
    command: serve-rest -c "/etc/config.yaml"
    ports:
      - "3002:3002"
    volumes:
      - ./config.yaml:/etc/config.yaml

  task:
    build:
      context: ./task
      dockerfile: Dockerfile
    image: backaged/carpediem-task:v1
    command: serve-rest -c "/etc/config.yaml"
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./config.yaml:/etc/config.yaml
    
  redis:
    image: "redis:alpine"
    restart: always
    ports: 
      - "6379:6379"

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    